AllCops:
  NewCops: enable

require: rubocop-rspec

Metrics:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
